// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuckaobhpaguydfpntvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1Y2thb2JocGFndXlkZnBudHZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNzU4NzIsImV4cCI6MjA2ODY1MTg3Mn0.mxMuKFqvLEGTppUBpBA4ru8JGITSuCC5p1t7Zn8xU_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});