// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcyoexzcfcvvhvvodkjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jeW9leHpjZmN2dmh2dm9ka2pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTI1MzIsImV4cCI6MjA2OTM2ODUzMn0.xOQX5YemT7HLZ6zZ0jH0hIE3e42Dck18V603mErI2ok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});